server:
  port: 9040

spring:
  application:
    name: course
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:course;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  instance:
    host: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:9030/eureka