server:
  port: 9040

spring:
  application:
    name: course
  datasource:
    driver-class-name: org.h2.Driver  
    url: jdbc:h2:file:./data/course;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
    spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

eureka:
  instance:
    host: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:9030/eureka